# Server properties
server:
  servlet:
    context-path: /api-estudiantes
  port: 8080
# Spring properties
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-3-227-195-74.compute-1.amazonaws.com:5432/d817rirfmh412v
    driver-class-name: org.postgresql.Driver
    username: qioirhrduepnky
    password: 7e69def64fffee0883c6aefd1357493b4ce863c937df1ff49712d1c21f2789b0

logging:
  level:
    root: INFO
    
  file:
    name: Estudiantes.log
    root: ERROR
  file:
    name: Estudiantes.log